extensions:
  # this dir must exist on filesystem where otelcollector is running
  file_storage:
    directory: /tmp/otc
    timeout: 10s

receivers:
  journald:
    directory: /var/log/journal/
    units:
      - kepler
    priority: info
  prometheus:
    config:
      scrape_configs:
        - job_name: 'kepler-local'
          scrape_interval: 5s
          static_configs:
            - targets: ['127.0.0.1:8888'] # kepler endpoint

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 95
    spike_limit_percentage: 25

exporters:
  otlphttp:
    endpoint: https://OCP_ROUTE_OTELCOL
    tls:
      insecure: false
      cert_file: /tmp/demoCA/server.crt
      key_file: /tmp/demoCA/server.key
      ca_file: /tmp/demoCA/ca.crt
  debug:
    verbosity: detailed

service:
  extensions: [file_storage]
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8887
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch, memory_limiter]
      exporters: [otlphttp, debug]
