extensions:
  # TODO: replace basicauth
  basicauth/client:
    client_auth:
      username: rhel
      password: rhel
  # bearertokenauth:
  #   filename: /conf/edge-token
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'pmproxy-rhedge'
        scrape_interval: 5s
        static_configs:
        - targets: ['127.0.0.1:44322'] # instrumented app endpoint
processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 95
    spike_limit_percentage: 25
exporters:
  otlphttp:
    #endpoint: https://OCP_ROUTE_OTELCOL
    endpoint: https://otlp-https.apps.open-svc-sts.k1wl.p1.openshiftapps.com # otel-collector service route from OCP, port 4318
    auth:
      authenticator: basicauth/client
    tls:
      insecure: false
      ca_file: /conf/ca.crt
  logging:
    verbosity: detailed
service:
  #extensions: [bearertokenauth]
  extensions: [basicauth/client]
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8887
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlphttp]
