extensions:
  file_storage:
    # this dir must exist on filesystem where otelcollector is running
    directory: /otc
    timeout: 10s
receivers:
  journald:
    directory: /var/log/journal/
    units:
      - ssh
      #- microshift
      #- ovn-kubernetes
      #- crio
    priority: info
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12334
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kepler-local'
        scrape_interval: 5s
        static_configs:
        - targets: ['127.0.0.1:8888'] # kepler as host systemd service
      - job_name: 'pmproxy-rhedge'
        scrape_interval: 5s
        static_configs:
        - targets: ['0.0.0.0:44322'] # pcp

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_percentage: 95
    spike_limit_percentage: 25
exporters:
  otlphttp:
    endpoint: https://otlp-https.<base_domain>
    #endpoint: https://otlp-https.apps.open-svc-sts.k1wl.p1.openshiftapps.com
    headers:
      x-scope-orgid: "infrastructure"
    tls:
      insecure: false # TODO
      cert_file: "/path/to/server-cert.pem"
      key_file: "/path/to/server-key.pem"
      client_ca_file: "/path/to/client-ca.pem"
    sending_queue:
      storage: file_storage
  logging:
    verbosity: detailed
service:
  extensions: [file_storage]
  telemetry:
    metrics:
      level: detailed
      address: 0.0.0.0:8887
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [otlphttp]
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    logs:
      receivers: [journald,otlp]
      exporters: [otlphttp]
