apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: tempostack
  namespace: observability
spec:
  observability:
    tracing:
      jaeger_agent_endpoint: 'localhost:6831'
  resources:
    total:
      limits:
        cpu: '2'
        memory: 2Gi
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  limits:
    global:
      ingestion: {}
  template:
    queryFrontend:
      jaegerQuery:
        enabled: true
        ingress:
          type: route
  replicationFactor: 1
  storage:
    secret:
      name: minio-tempo
      type: s3
  storageSize: 1Gi
  retention:
    global:
      traces: 48h0m0s
