apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: observability
resources:
- serviceaccount.yaml
- otelcol-cabundle.yaml
- otel-collector.yaml
- tls-otel-collector-route.yaml
