apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: observability
resources:
- otelcol-cabundle.yaml
# mTLS configmaps clientca & tls-otelcol must exist before applying
- otel-collector.yaml
