apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: observability
resources:
- serviceaccount.yaml
- otelcol-cabundle.yaml
# mTLS configmaps clientca & tls-otelcol must exist before applying
- otel-collector.yaml
# Must replace $APPS_DOMAIN in route manifest before applying
- otel-collector-route.yaml
