apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otlp-receiver
  namespace: observability
spec:
  config: |
    receivers:
      otlp:
        protocols:
          http:
            tls:
              cert_file: /certs/server.crt
              key_file: /certs/server.key
              client_ca_file: /certs/ca.crt
          grpc:
            tls:
              cert_file: /certs/server.crt
              key_file: /certs/server.key
              client_ca_file: /certs/ca.crt
    exporters:
      otlp:
        endpoint: "tempo-tempostack-distributor.observability.svc:4317"
        tls:
          insecure: true
      debug:
        verbosity: detailed
      otlp/1:
        endpoint: "jaeger-allinone-collector.observability.svc:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [debug, otlp]
  ingress:
    route:
      termination: passthrough
    type: route
  mode: deployment
  volumeMounts:
  - mountPath: /etc/pki/ca-trust/source/service-ca
    name: otelcol-cabundle
  - mountPath: /certs
    name: mtls-certs
  volumes:
  - configMap:
      name: mtls-certs
    name: mtls-certs
  - configMap:
      name: otelcol-cabundle
    name: otelcol-cabundle
