apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: otc
  namespace: observability
spec:
  host: otc.${APPS_DOMAIN}
  port:
    targetPort: otlp-http
  tls:
    termination: passthrough
  to:
    kind: Service
    name: ingest-collector-headless
    weight: 100
  wildcardPolicy: None
