apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otlp-receiver
  namespace: observability
spec:
  config:
    exporters:
      debug:
        verbosity: detailed
      otlp:
        endpoint: tempo-tempostack-distributor.observability.svc:4317
        tls:
          insecure: true
      otlp/1:
        endpoint: jaeger-allinone-collector.observability.svc:4317
        tls:
          insecure: true
      prometheus:
        add_metric_suffixes: false
        endpoint: 0.0.0.0:8889
        metric_expiration: 180m
        resource_to_telemetry_conversion:
          enabled: true
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
            tls:
              cert_file: /certs/server.crt
              client_ca_file: /certs/ca.crt
              key_file: /certs/server.key
          http:
            endpoint: 0.0.0.0:4318
            tls:
              cert_file: /certs/server.crt
              client_ca_file: /certs/ca.crt
              key_file: /certs/server.key
    service:
      pipelines:
        metrics:
          exporters:
          - debug
          - prometheus
          receivers:
          - otlp
        traces:
          exporters:
          - debug
          - otlp
          receivers:
          - otlp
      telemetry:
        metrics:
          address: 0.0.0.0:8888
  ingress:
    route:
      termination: passthrough
    type: route
  ipFamilyPolicy: SingleStack
  mode: deployment
  observability:
    metrics:
      enableMetrics: true
  targetAllocator:
    allocationStrategy: consistent-hashing
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      podMonitorSelector: {}
      scrapeInterval: 30s
      serviceMonitorSelector: {}
    resources: {}
  upgradeStrategy: automatic
  volumeMounts:
  - mountPath: /etc/pki/ca-trust/source/service-ca
    name: otelcol-cabundle
  - mountPath: /certs
    name: mtls-certs
  volumes:
  - secret:
      secretName: mtls-certs
    name: mtls-certs
  - configMap:
      name: otelcol-cabundle
    name: otelcol-cabundle
