{
 "title": "PCP Prometheus Host Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "host", "query": { "query": "label_values(hostname)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Load average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_all_load{hostname=\"$host\"}",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem_util_free{hostname=\"$host\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mem_util_cached{hostname=\"$host\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "mem_physmem{hostname=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Per-CPU busy (User)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_percpu_cpu_user{hostname=\"$host\"}[$__rate_interval])/1000",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  {
   "title": "Per-CPU busy (Sys)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_percpu_cpu_sys{hostname=\"$host\"}[$__rate_interval])/1000",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  { "title": "Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Context switches per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(kernel_all_pswitch{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "kernel_all_pswitch"
    }
   ]
  },
  {
   "title": "Runnable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kernel_all_runnable{hostname=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem_util_used{hostname=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem_util_cached{hostname=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "expr": "mem_util_free{hostname=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Page fault rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mem_vmstat_pgfault{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "mem_vmstat_pgfault"
    }
   ]
  },
  {
   "title": "Hard fault rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mem_vmstat_pgmajfault{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "mem_vmstat_pgmajfault"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Network Throughput (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_in_bytes{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  {
   "title": "Network Throughput (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_out_bytes{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  {
   "title": "Network Drops (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_in_drops{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  {
   "title": "Network Drops (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_out_drops{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  {
   "title": "Network Packets (In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_in_packets{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  {
   "title": "Network Packets (Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(network_interface_out_packets{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{instname}}"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "TCP Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(network_tcp_timeouts{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "network_tcp_timeouts"
    }
   ]
  },
  {
   "title": "TCP Listen Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(network_tcp_listendrops{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "network_tcp_listendrops"
    },
    {
     "expr": "rate(network_tcp_listenoverflows{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "network_tcp_listenoverflows"
    }
   ]
  },
  {
   "title": "TCP Retransmits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(network_tcp_retranssegs{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "network_tcp_retranssegs"
    },
    {
     "expr": "rate(network_tcp_fastretrans{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "network_tcp_fastretrans"
    },
    {
     "expr": "rate(network_tcp_slowstartretrans{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "network_tcp_slowstartretrans"
    },
    {
     "expr": "rate(network_tcp_synretrans{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "network_tcp_synretrans"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Disk Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(disk_dev_read_rawactive{hostname=\"$host\"}[$__rate_interval])/1000",
     "legendFormat": "read {{instname}}"
    },
    {
     "expr": "rate(disk_dev_write_rawactive{hostname=\"$host\"}[$__rate_interval])/1000",
     "legendFormat": "write {{instname}}"
    }
   ]
  },
  {
   "title": "Disk IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 77 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(disk_dev_read{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "read {{instname}}"
    },
    {
     "expr": "rate(disk_dev_write{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "write {{instname}}"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "KiBs" }
   ],
   "targets": [
    {
     "expr": "rate(disk_dev_read_bytes{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "read {{instname}}"
    },
    {
     "expr": "rate(disk_dev_write_bytes{hostname=\"$host\"}[$__rate_interval])",
     "legendFormat": "write {{instname}}"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(disk_dev_avactive{hostname=\"$host\"}[$__rate_interval])/1000",
     "legendFormat": "{{instname}}"
    }
   ]
  }
 ]
}