# 1. Grant `cluster-monitoring-view` role to the `mygrafana-sa`
#  oc adm policy add-cluster-role-to-user cluster-monitoring-view -z mygrafana-sa
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      dashboards: mygrafana   # This label matches the mygrafana Grafana instance
  datasource:
    name: prometheus
    access: proxy
    editable: true
    type: prometheus
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    isDefault: true
    jsonData:
      httpHeaderName1: 'Authorization'
      timeInterval: 5s
      tlsSkipVerify: true
      name: Prometheus
    secureJsonData:
      httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
    name: prometheus.yaml
