apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
namespace: observability
resources:
- minio-secret-loki.yaml
- minio-loki-pvc.yaml
- minio-loki-svc.yaml
- minio-loki.yaml
- lokistack.yaml
