kind: Service
apiVersion: v1
metadata:
  name: minio-loki
  namespace: observability
spec:
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: minio-loki
