---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kepler
  name: otelcol
  labels:
    otel: collect
data:
  otelconfig.yaml: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:
      prometheus:
        config:
          scrape_configs:
          - job_name: 'kepler'
            scrape_interval: 10s
            static_configs:
            - targets: ['localhost:9102'] # application metrics endpoint
    processors:
      memory_limiter:
        check_interval: 5s
        limit_percentage: 95
        spike_limit_percentage: 25
      batch:
    exporters:
      logging:
        verbosity: detailed
      otlphttp:
        #endpoint: https://OCP_ROUTE_OTELCOL
        endpoint: https://otc.apps.open-svc-sts.k1wl.p1.openshiftapps.com # otel-collector service route from OCP, port 4318
        tls:
          insecure: false
          cert_file: /conf/tls/client.cert.pem
          key_file: /conf/tls/client.key.pem
          ca_file: /conf/server.cert.pem
    service:
      telemetry:
        logs:
          level: info
      #extensions: [bearertokenauth, basicauth/client]
      pipelines:
        metrics:
          receivers: [prometheus]
          exporters: [otlphttp]

