apiVersion: monitoring.rhobs/v1alpha1
kind: MonitoringStack
metadata:
  name: sample-monitoring-stack
  labels:
    mso: example
  namespace: observability
spec:
  alertmanagerConfig:
    disabled: true
  logLevel: debug
  prometheusConfig:
    replicas: 1
    enableRemoteWriteReceiver: true
  resourceSelector:
    matchLabels:
      app: demo
  retention: 1d
